# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenWeatherApp
  
  # Lottie is a mobile library for Android and iOS that natively renders vector based animations and art in realtime with minimal code. https://github.com/airbnb/lottie-ios

  pod 'lottie-ios'
  
end
